application: homework8-163001
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: frontEnd/HW8.html
  upload: frontEnd/HW8.html
 
- url: /(.+\.php)$
  script: \1

- url: /(.*)
  static_files: frontEnd/\1
  upload: frontEnd/(.*)
  


  

  

